# Generated by Django 5.1.4 on 2025-01-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_education_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
    ]
