# Generated by Django 5.1.4 on 2025-01-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_work_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('ordinal', models.IntegerField()),
            ],
        ),
    ]
