# Generated by Django 5.1.4 on 2025-01-10 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='image',
        ),
    ]
