# Generated by Django 5.1.4 on 2025-01-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_skills_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='level',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
