# Generated by Django 5.1.4 on 2025-01-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_skills_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='years',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
